### PR TITLE
Sphere diffusion

### PR DESCRIPTION
**Pull request by tinosulzer**
Changes for the case where spherical linear laplacian is multiplied by a constant scalar e.g.
```julia
Dt(u(t,r)) ~ 4/r^2 * Dr(r^2 * Dr(u(t,r)))
```
This enables solving SPM and SPMe

### CODE REVIEW

**Comment by ChrisRackauckas** [comment]
Test failures expected?

**Comment by tinosulzer** [comment]
No, must have had an old version for local testing, looking into it now

**Comment by tinosulzer** [comment]
It broke because (r^2)^-1 is now converted to r^-2 and @rule can't deal with that, fixed now but tests are failing locally for me for a different reason in MOL_1D_Nonlinear_Diffusion.jl

**Comment by tinosulzer** [comment]
It no longer likes this construct:
```julia
    @variables u[1:Nx](t)
    sol′ = [sol[u[i]][end] for i in 1:Nx]
    @test asf ≈ sol′ atol=0.1
```

**Comment by ChrisRackauckas** [comment]
Yeah that's now a symbolic array. Just bound until we update it.

**Comment by ChrisRackauckas** [comment]
How are you even able to use Symbolics.jl v1 here though? That's a bit odd.

**Comment by tinosulzer** [comment]
Where is the Symbolics dependency coming from?
Can we merge this and fix the symbolic arrays separately?

**Comment by tinosulzer** [comment]
> Just bound until we update it

I don't know what this means - is it referring to version number in the Project.toml?

**Comment by ChrisRackauckas** [comment]
Yeah, bound to not allow MTK v5.27 for now.

**Comment by tinosulzer** [comment]
I now have permissions to merge this but should I wait for review first?

**Comment by ChrisRackauckas** [comment]
Feel free to go for it if all tests are passing.

**Pull request merged**
