### PR TITLE
Nonuniform complete derivative operator constructors

### PR DESCRIPTION
**Pull request by xtalax**

### CODE REVIEW

**Comment by ChrisRackauckas** [comment]
What are the "complete" operators?

**Comment by xtalax** [comment]
Simply operators that also contain stencils for the 'ghost nodes', to support derivatives in the boundary conditions

**Comment by ChrisRackauckas** [comment]
Add docs?

**Comment by xtalax** [comment]
They're pretty much internal use only, the only methods using them are in MOL

**Pull request merged**
