### PR TITLE
Use JuliaGPU's GitLab CI setup

### PR DESCRIPTION
**Pull request by christopher-dG**

### CODE REVIEW

**Comment by christopher-dG** [comment]
This one appears to not actually have a GPU group defined in the tests.

**Comment by ChrisRackauckas** [comment]
Yes, this isn't quite used yet, mostly because when it was getting setup is when we found the CI issues

**Comment by christopher-dG** [comment]
This one should be ready, the Travis failure looks unrelated.

**Comment by ChrisRackauckas** [comment]
Yes, this repo needs a bit of help, but that's not your problem. Thanks!

**Pull request merged**
