### PR TITLE
Concretizations : decreasing bandwidths of operators & restructuring for Biased Upwind

### PR DESCRIPTION
**Pull request by mjsheikh**

### CODE REVIEW

**Comment by ChrisRackauckas** [comment]
This looks good. What's the WIP?

**Comment by mjsheikh** [comment]
Isn't much, I feel the `AffineBC` concretizations require a bit more testing.

**Comment by mjsheikh** [comment]
@ChrisRackauckas This should address much of #182 along with updating concretizations for UpwindDifference since we added the offside feature.

**Comment by ChrisRackauckas** [comment]
awesome, looks good!

**Pull request merged**
