### PR TITLE
Optimizing convolutions

### PR DESCRIPTION
**Pull request by mjsheikh**
This a trial run for potential future PR CI-check fails

### CODE REVIEW

**Comment by mjsheikh** [comment]
- [HybridArrays.jl](https://github.com/mateuszbaran/HybridArrays.jl) has some nice ways to be used as a substitute for StaticArrays.jl, atleast at places where we wish to make Arrays[StaticArrays]. Hence, here I've provided that replacement at places where it would atleast not break while being accessed by other functions. 
-  `coeff_func` default has been changed from `nothing` to `1` so that lesser conditionals are required during vectorization. This also fixed broken tests of `2D_3D Multiplication` 
- Used `@turbo` in convolutions for `CenteredDifference`. `UpwindDifference` has too many conditionals that would make vectorization ineffective. Observed speed-up of about **2x**
- Improvements in benchmarks of `DerivativeOperator` struct allocations shown for  a grid of size 100. These will help in VCOps as well.
  Speed-up of about **2x** for uniform grid convolutions.
- **Earlier**
```
1. Uniform grid
  @btime A = CenteredDifference(1,4,dx,length(u0).-2) 
  7.886 μs (65 allocations: 4.63 KiB)
  
  @btime u = A*u0
  851.323 ns (4 allocations: 1.17 KiB)
  
  @btime A = UpwindDifference(1,4,dx,length(u0).-2)
  16.534 μs (138 allocations: 11.45 KiB)
  
2. Padded Uniform grid
  @btime A = CenteredDifference(1,4,dx,length(u0))
  7.657 μs (63 allocations: 4.56 KiB)
  
  @btime u = A*bc*u0
  533.983 ns (4 allocations: 1.28 KiB)
  
3. Non-Uniform grid
  @btime A = CenteredDifference(1,4,dx,length(u0).-2) 
  141.625 μs (1257 allocations: 96.42 KiB)
  
  @btime u = A*u0
  782.067 ns (4 allocations: 1.14 KiB)
  
4. Padded Non-uniform grid
  @btime A = CenteredDifference(1,4,dx,length(u0).-2)
  135.295 μs (1233 allocations: 94.58 KiB)
 
  @btime u = A*bc*u0
  613.607 ns (4 allocations: 1.25 KiB)
```
  
- **Now**
```
1. Uniform grid
  @btime A = CenteredDifference(1,4,dx,length(u0).-2) 
  6.355 μs (48 allocations: 4.27 KiB)
  
  @btime u = A*u0
  313.949 ns (4 allocations: 1.13 KiB)
   
  @btime B = UpwindDifference(1,4,dx,length(u0))
  14.700 μs (118 allocations: 9.83 KiB)
  
2. Padded Uniform grid
  @btime A = CenteredDifference(1,4,dx,length(u0))
  5.861 μs (46 allocations: 4.20 KiB)
  
  @btime u = A*bc*u0
  291.655 ns (4 allocations: 1.23 KiB)
  
3. Non-uniform grid
  @btime A = CenteredDifference(1,4,dx,length(u0).-2)
  136.904 μs (1240 allocations: 96.06 KiB)
  
  @btime u = A*u0
  590.308 ns (4 allocations: 1.09 KiB)
  
4. Padded Non-uniform grid
  @btime A = CenteredDifference(1,4,dx,length(u0).-2)
  137.185 μs (1216 allocations: 94.22 KiB)
  
  @btime u = A*bc*u0
  557.472 ns (3 allocations: 1.06 KiB)

```

**Comment by ChrisRackauckas** [comment]
Where is the HybridArray dynamism used?

**Comment by mjsheikh** [comment]
> Where is the HybridArray dynamism used?

While declaring structs of `CenteredDifference` & uniform grid `UpwindDifference` . Wherever we have stencils of the form `SVector[SVectors]`, that has been replaced with `HybridArray{Tuple{StaticArrays.Dynamic()}}`. Some reduction in allocations for Operator structures can be seen because of that.

**Comment by ChrisRackauckas** [comment]
But that makes the struct non-isbits. Keeping it as a static array of static arrays is probably better for distributed use.

**Comment by mjsheikh** [comment]
Oh, is that so? Then I'll revert back those changes.

**Comment by ChrisRackauckas** [comment]
Yeah, the thing is that static arrays are bitstypes, so in this form it's fully bitstype with no pointers at all. So the entire thing can live on the stack. In practice what this means is that if you use it as a temporary, Julia can actually elide its entire construction and eliminate its allocation in many circumstances, making it be something free to construct and destroy and thus more of an abstraction. Not all benchmarks will catch that though (and the compiler may decide it's not worth doing).

**Pull request merged**
