### PR TITLE
Add aqua tests

### PR DESCRIPTION
**Pull request by charleskawczynski**
This PR adds some aqua tests. I'm happy to help chip away at some of the performance-related ones in subsequent PRs.

### CODE REVIEW

**Comment by ChrisRackauckas** [comment]
> I'm happy to help chip away at some of the performance-related ones in subsequent PRs.

That would be greatly helpful. Though, are you still using DiffEqOperators? This library was largely obsoleted by SciMLOperators quite some time ago for most things, so I am a bit confused to see this getting some activity.

**Comment by charleskawczynski** [comment]
> That would be greatly helpful. Though, are you still using DiffEqOperators? This library was largely obsoleted by SciMLOperators quite some time ago for most things, so I am a bit confused to see this getting some activity.

Ah, ok. We’re not using it directly, but we must be using it indirectly because I noticed some unbound arg warnings when updating dependencies

**Comment by ChrisRackauckas** [comment]
https://juliahub.com/ui/Packages/DiffEqOperators/Vx3Cs/4.45.0?page=2 most of the dependents that are SciML don't use it these days, so I'm not sure where it would come into a dependency tree. What's the project.toml that is associated with that?

**Comment by charleskawczynski** [comment]
I don’t see any of them at first glance, I’ll take a closer look when I’m at my computer next

**Comment by charleskawczynski** [comment]
Weird, I'm not seeing `DiffEqOperators` in the manifest 🤷🏻

**Comment by charleskawczynski** [comment]
Maybe I had an old manifest or something. I’m fine with closing if this is being deprecated

**Pull request closed without merging**
